In [2]:
mensagem = "abc"
print(mensagem)

abc


In [3]:
# ord() retorna o valor ASCII de um caractere
ord('a')

97

In [4]:
# conversão para binário
f"{97:b}"

'1100001'

In [4]:
# conversão para octal
f"{97:8b}"

' 1100001'

In [5]:
# 
f'{ord('a'):08b}'

'01100001'

In [6]:
mensagem_binario = ""
for letra in mensagem:
    # print(letra, f"{ord(letra):08b}")
    mensagem_binario += f"{ord(letra):08b}"
print(mensagem_binario)

011000010110001001100011


In [7]:
mensagem_binario += "1"
print(mensagem_binario)

0110000101100010011000111


In [8]:
import numpy as np

In [9]:
nc = len(mensagem)
print(nc)

3


In [10]:
# nb = número de blocos

nb = int(np.ceil(0.015625 * nc + 0.140625))
print(nb)

1


In [11]:
# 

k = (512 * nb - 64) % (512 * nb) - 8 * nc - 1
print(k)

423


In [12]:
"0" * k

'000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'

In [13]:
mensagem_binario += "0" * k
print(mensagem_binario)

0110000101100010011000111000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000


In [14]:
#  

print(len(mensagem_binario))

448


In [15]:
# 

mensagem_binario += f"{nc * 8:064b}"
print(mensagem_binario)

01100001011000100110001110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011000


In [16]:
print(len(mensagem_binario))

512


In [17]:
#

def mensagem_para_binario(mensagem):
    
    mensagem_binario = ""
    for letra in mensagem:
        mensagem_binario += f"{ord(letra):08b}"

    mensagem_binario += "1"

    nc = len(mensagem)
    nb = int(np.ceil(0.015625 * nc + 0.140625))
    k = (512 * nb - 64) % (512 * nb) - 8 * nc - 1

    mensagem_binario += "0" * k

    mensagem_binario += f"{nc * 8:064b}"

    return mensagem_binario, nb

In [18]:

mensagem_binario, nb = mensagem_para_binario(mensagem)
print(len(mensagem_binario), mensagem_binario)

512 01100001011000100110001110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011000


In [19]:
np.zeros(shape=(2,16), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.zeros(shape=(3,16), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
words = np.zeros(shape=(nb, 64), dtype=int)
words

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
words.shape

(1, 64)

In [23]:
512 / 32

16.0

In [24]:
mensagem_binario[0:32]

'01100001011000100110001110000000'

In [25]:
mensagem_binario[32:64]

'00000000000000000000000000000000'

In [26]:
mensagem_binario[64:96]

'00000000000000000000000000000000'

In [27]:
passo = 32

for indice_bloco in range(nb):
    binario_bloco = mensagem_binario[indice_bloco * 512:
                                     (indice_bloco + 1) * 512]
    i = 0
    j = i + passo
    k = 0
    while j <= 512:
        # print(k, i, j)
        # display(binario_bloco[i:j])
        # display(int(binario_bloco[i:j], 2))
        words[indice_bloco, k] = (int(binario_bloco[i:j], 2))

        i = j
        j = i + passo
        k += 1

In [28]:
print(words)

[[1633837952          0          0          0          0          0
           0          0          0          0          0          0
           0          0          0         24          0          0
           0          0          0          0          0          0
           0          0          0          0          0          0
           0          0          0          0          0          0
           0          0          0          0          0          0
           0          0          0          0          0          0
           0          0          0          0          0          0
           0          0          0          0          0          0
           0          0          0          0]]


In [29]:
def right_shift(x, n):
    return (x >> n)

In [30]:
def right_rotate(x, n):
    return x >> n | x << (32 - n)

In [31]:
def sigma_zero(word):
    return right_rotate(word, 7) ^ right_rotate(word, 18) ^ right_shift(word, 3)

In [32]:
def sigma_um(word):
    return right_rotate(word, 17) ^ right_rotate(word, 19) ^ right_shift(word, 10)

In [33]:
for indice_bloco in range(nb):
    # print(indice_bloco)
    for indice_word in range(16, 64):
        # print(indice_word)
        w1 = words[indice_bloco, indice_word - 2]
        w2 = words[indice_bloco, indice_word - 7]
        w3 = words[indice_bloco, indice_word - 15]
        w4 = words[indice_bloco, indice_word - 16]

        soma_final = (sigma_um(w1) + w2 + sigma_zero(w3) + w4) % 2**32
        words[indice_bloco, indice_word] = soma_final

display(words)

array([[1633837952,          0,          0,          0,          0,
                 0,          0,          0,          0,          0,
                 0,          0,          0,          0,          0,
                24, 1633837952,     983040, 2108187653, 1610613702,
        1050508152,   25426944,  316456923, 3806512014, 3357629466,
        3073800610, 3854317833,  845560923, 2636160359, 3968280267,
        1881225380, 3552024379, 2482346367,  996719219, 2952069057,
        4043988066,  176896406, 1924104970, 2483675966,  610538786,
        2672279444, 4037431130, 1042573945,  657669027,  206005234,
        2215296807, 2049510749,  106709978, 4215179723, 3430291419,
        3118885940, 2845390439, 2226839261, 3256115900,  344409900,
        2987358873, 4015503821, 3957764664, 2682456414, 2025622859,
        2755645205, 1720397816, 4004225740,  313650667]])

In [34]:
for indice_bloco in range(nb):
    for indice_word in range(0, 64):
        print(f"{words[indice_bloco, indice_word]:08x}")

61626380
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000000
00000018
61626380
000f0000
7da86405
600003c6
3e9d7b78
0183fc00
12dcbfdb
e2e2c38e
c8215c1a
b73679a2
e5bc3909
32663c5b
9d209d67
ec8726cb
702138a4
d3b7973b
93f5997f
3b68ba73
aff4ffc1
f10a5c62
0a8b3996
72af830a
9409e33e
24641522
9f47bf94
f0a64f5a
3e246a79
27333ba3
0c4763f2
840abf27
7a290d5d
065c43da
fb3e89cb
cc7617db
b9e66c34
a9993667
84badedd
c21462bc
1487472c
b20f7a99
ef57b9cd
ebe6b238
9fe3095e
78bc8d4b
a43fcf15
668b2ff8
eeaba2cc
12b1edeb


In [35]:

def gerar_words(mensagem_binario, nb):
    words = np.zeros(shape=(nb, 64), dtype=int)

    passo = 32
    for indice_bloco in range(nb):
        binario_bloco = mensagem_binario[indice_bloco * 512:
                                        (indice_bloco + 1) * 512]
        i = 0
        j = i + passo
        k = 0
        while j <= 512:
            words[indice_bloco, k] = int(binario_bloco[i:j], 2)

            i = j
            j = i + passo
            k += 1
    

    for indice_bloco in range(nb):
        for indice_word in range(16, 64):
            w1 = words[indice_bloco, indice_word - 2]
            w2 = words[indice_bloco, indice_word - 7]
            w3 = words[indice_bloco, indice_word - 15]
            w4 = words[indice_bloco, indice_word - 16]

            soma_final = (sigma_um(w1) + w2 + sigma_zero(w3) + w4) % 2 ** 32
            words[indice_bloco, indice_word] = soma_final

    return words

In [36]:
mensagem = "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"
nc = len(mensagem)
mensagem_binario, nb = mensagem_para_binario(mensagem)
words = gerar_words(mensagem_binario, nb)
display(words)

array([[1633837924, 1650680933, 1667523942, 1684366951, 1701209960,
        1718052969, 1734895978, 1751738987, 1768581996, 1785425005,
        1802268014, 1819111023, 1835954032, 1852797041, 2147483648,
                 0, 3951039149, 2814619282, 1994996642, 3124946755,
        2460557828, 3628590942, 2652241974, 2994776011, 3723171094,
        4083517172, 2526859336, 3914979741, 1791803628, 4115443864,
         720483034, 3998860489, 2822103402,  503268393, 3605092697,
        3281505646, 1863844298,  559366661,  905935492, 2537811576,
        3829498855,  218755085, 2626269012,   70081519, 1911633104,
         261420131, 2118769763, 1868941719,  191915395,  395514570,
        1345344745, 3121765433, 2123600585, 3586894366, 2027968605,
        4142358812, 2328375502, 2336727811, 4251869823, 2356030570,
        1073851889,  440258711, 2849992546, 1789266489],
       [         0,          0,          0,          0,          0,
                 0,          0,          0,          0,    

In [37]:
from sympy import primerange

In [38]:
primos = np.array(list(primerange(1, 1000))[:64], dtype=int)
print(f"{len(primos)} primeiros primos: \n", primos)

64 primeiros primos: 
 [  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251
 257 263 269 271 277 281 283 293 307 311]


In [39]:
constantes_h = []
constantes_k = []

for i, primo in enumerate(primos):
    parte_um = np.sqrt(primo) - int(np.sqrt(primo))
    parte_dois = parte_um * 2 ** 32
    parte_tres = int(parte_dois)

    if i < 8:
        # print(f"{parte_tres:08x}")
        constantes_h.append(parte_tres)
        # continue

    # break

    parte_um = np.cbrt(primo) - int(np.cbrt(primo))
    parte_dois = parte_um * 2 ** 32
    parte_tres = int(parte_dois)
    constantes_k.append(parte_tres)

    

In [40]:
print(*constantes_h, sep="\n")

1779033703
3144134277
1013904242
2773480762
1359893119
2600822924
528734635
1541459225


In [41]:
print(*constantes_k, sep="\n")

1116352408
1899447441
3049323471
3921009573
961987163
1508970993
2453635748
2870763221
3624381080
310598401
607225278
1426881987
1925078388
2162078206
2614888103
3248222580
3835390401
4022224774
264347078
604807628
770255983
1249150122
1555081692
1996064986
2554220882
2821834349
2952996808
3210313671
3336571891
3584528711
113926993
338241895
666307205
773529912
1294757372
1396182291
1695183700
1986661051
2177026350
2456956037
2730485921
2820302411
3259730800
3345764771
3516065817
3600352804
4094571909
275423344
430227734
506948616
659060556
883997877
958139571
1322822218
1537002063
1747873779
1955562222
2024104815
2227730452
2361852424
2428436474
2756734187
3204031479
3329325298


In [42]:
def funcao_ch(x, y, z):
    return (x & y) ^ (~x & z)

def funcao_maj(x, y, z):
    return (x & y) ^ (x & z) ^ (y & z)

def funcao_s0(x):
    return right_rotate(x, 2) ^ right_rotate(x, 13) ^ right_rotate(x, 22)

def funcao_s1(x):
    return right_rotate(x, 6) ^ right_rotate(x, 11) ^ right_rotate(x, 25)

In [43]:
for i in range(nb):
    a = constantes_h[0]
    b = constantes_h[1]
    c = constantes_h[2]
    d = constantes_h[3]
    e = constantes_h[4]
    f = constantes_h[5]
    g = constantes_h[6]
    h = constantes_h[7]

    for j in range(64):
        ch = funcao_ch(e, f, g)
        maj = funcao_maj(a, b, c)
        s0 = funcao_s0(a)
        s1 = funcao_s1(e)

        t1 = (h + s1 + ch + constantes_k[j] + words[i, j]) % 2 ** 32
        t2 = (s0 + maj) % 2 ** 32

        h = g
        g = f
        f = e
        e = (d + t1) % 2 ** 32
        d = c
        c = b
        b = a
        a = (t1 + t2) % 2 ** 32

    constantes_h[0] = (constantes_h[0] + a) % 2 ** 32
    constantes_h[1] = (constantes_h[1] + b) % 2 ** 32
    constantes_h[2] = (constantes_h[2] + c) % 2 ** 32
    constantes_h[3] = (constantes_h[3] + d) % 2 ** 32
    constantes_h[4] = (constantes_h[4] + e) % 2 ** 32
    constantes_h[5] = (constantes_h[5] + f) % 2 ** 32
    constantes_h[6] = (constantes_h[6] + g) % 2 ** 32
    constantes_h[7] = (constantes_h[7] + h) % 2 ** 32

display(constantes_h)


[np.int64(613247585),
 np.int64(3523623096),
 np.int64(3854575251),
 np.int64(205414457),
 np.int64(2738676825),
 np.int64(1694441831),
 np.int64(4142722516),
 np.int64(433784513)]

In [44]:
"".join(f"{word:08x}" for word in constantes_h)

'248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1'

In [45]:
def sha256(mensagem, mensagem_binario=""):

    if mensagem_binario == "":
        mensagem_binario, nb = mensagem_para_binario(mensagem)
    else:

        if len(mensagem_binario) % 512 != 0:
            raise ValueError("A mensagem binaria deve conter um número de caracteres multiplo de 512")

        nb = len(mensagem_binario) // 512
    
    words = gerar_words(mensagem_binario, nb)

    primos = np.array(list(primerange(1, 1000))[:64], 
                  dtype=int)
    
    constantes_h = []
    constantes_k = []
    for i, primo in enumerate(primos):
        parte_um = np.sqrt(primo) - int(np.sqrt(primo))
        parte_dois = parte_um * 2 ** 32
        parte_tres = int(parte_dois)

        if i < 8:
            # print(f"{parte_tres:08x}")
            constantes_h.append(parte_tres)
            # continue

        # break
        parte_um = np.cbrt(primo) - int(np.cbrt(primo))
        parte_dois = parte_um * 2 ** 32
        parte_tres = int(parte_dois)
        constantes_k.append(parte_tres)

    for i in range(nb):
        a = constantes_h[0]
        b = constantes_h[1]
        c = constantes_h[2]
        d = constantes_h[3]
        e = constantes_h[4]
        f = constantes_h[5]
        g = constantes_h[6]
        h = constantes_h[7]

        for j in range(64):

            ch = funcao_ch(e, f, g)
            maj = funcao_maj(a, b, c)
            s0 = funcao_s0(a)
            s1 = funcao_s1(e)

            t1 = (h + s1 + ch + constantes_k[j] + words[i, j]) % 2 ** 32
            t2 = (s0 + maj) % 2 ** 32

            h = g
            g = f
            f = e
            e = (d + t1) % 2 ** 32
            d = c
            c = b
            b = a
            a = (t1 + t2) % 2 ** 32
        
        constantes_h[0] = (constantes_h[0] + a) % 2 ** 32
        constantes_h[1] = (constantes_h[1] + b) % 2 ** 32
        constantes_h[2] = (constantes_h[2] + c) % 2 ** 32
        constantes_h[3] = (constantes_h[3] + d) % 2 ** 32
        constantes_h[4] = (constantes_h[4] + e) % 2 ** 32
        constantes_h[5] = (constantes_h[5] + f) % 2 ** 32
        constantes_h[6] = (constantes_h[6] + g) % 2 ** 32
        constantes_h[7] = (constantes_h[7] + h) % 2 ** 32

    return "".join(f"{word:08x}" for word in constantes_h)

In [46]:
sha256("abc")

'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad'

In [47]:
sha256("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq")

'248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1'

In [48]:
transacoes = [
    "Alice paga 5 bitcoins para Bob",
    "Bob paga 3 bitcoins para Carol",
    "Carol paga 1 bitcoin para Alice",
    "Alice paga 2 bitcoins para Bob",
    "Bob paga 4 bitcoins para Carol",
]

In [49]:
if len(transacoes) % 2 != 0:
    transacoes.append(transacoes[-1])

transacoes

['Alice paga 5 bitcoins para Bob',
 'Bob paga 3 bitcoins para Carol',
 'Carol paga 1 bitcoin para Alice',
 'Alice paga 2 bitcoins para Bob',
 'Bob paga 4 bitcoins para Carol',
 'Bob paga 4 bitcoins para Carol']

In [50]:
hashes_transacoes = []

for transacao in transacoes:
    tx_id = sha256(transacao)
    hashes_transacoes.append(tx_id)

print(*hashes_transacoes, sep= "\n")

c87a0bc7703ce549baaebde2df87217f637c878dd2b4f26b51e18230d481c068
e3433713c693c0aaaab8e58813f989b4effd3475a5148eb2e7a03a024f21d71e
42bf14e5caa750b61be231babc439e41ada94ddc9bc7e3c6dc9d5ebcfb584c9d
e0e27682ebd9d4f181835b992300a487f7349530b723c0eabeb7103ab51d3cee
deab944cce03e0ac72a17eb18af897495b1df318f6368fa221f74287da04783e
deab944cce03e0ac72a17eb18af897495b1df318f6368fa221f74287da04783e


In [51]:
from copy import deepcopy

In [55]:
nivel_anterior = deepcopy(hashes_transacoes)
nivel_atual = []
passo = 2

while len(nivel_anterior) > 1:
    
    i = 0
    j = i + passo
    
    if len(nivel_anterior) % 2 != 0:
        nivel_anterior.append(nivel_anterior[-1])

    while j <= len(nivel_anterior):
        tx_id_um, tx_id_dois = nivel_anterior[i:j]
        hash_um_binario = f"{int(tx_id_um, 16):0256b}"
        hash_dois_binario = f"{int(tx_id_dois, 16):0256b}"

        binario_concatenado = f"{hash_um_binario}{hash_dois_binario}"
        novo_hash = sha256(mensagem="", mensagem_binario=binario_concatenado)
        nivel_atual.append(novo_hash)

        i = j
        j = i + passo
    
    nivel_anterior = deepcopy(nivel_atual)
    nivel_atual = []

nivel_anterior

['517b7d7df2bd00a0892ea438bbfec395bb06a75805ca976c02f0abdb4b5b97e6']

In [56]:
def arvore_merkle(transacoes):

    hashes_transacoes = []
    for transacao in transacoes:
        tx_id = sha256(transacao)
        hashes_transacoes.append(tx_id)
    
    nivel_anterior = deepcopy(hashes_transacoes)
    nivel_atual = []
    passo = 2

    while len(nivel_anterior) > 1:

        i = 0
        j = i + passo

        if len(nivel_anterior) % 2 != 0:
            nivel_anterior.append(nivel_anterior[-1])
        
        while j <= len(nivel_anterior):
            tx_id_um, tx_id_dois = nivel_anterior[i:j]
            
            hash_um_binario = f"{int(tx_id_um, 16):0256b}"
            hash_dois_binario = f"{int(tx_id_dois, 16):0256b}"

            binario_concatenado = f"{hash_um_binario}{hash_dois_binario}"
            novo_hash = sha256(mensagem="",
                            mensagem_binario=binario_concatenado)
            nivel_atual.append(novo_hash)

            i = j
            j = i + passo
        
        nivel_anterior = deepcopy(nivel_atual)
        nivel_atual = []

    return nivel_anterior

In [57]:
arvore_merkle(transacoes)

['517b7d7df2bd00a0892ea438bbfec395bb06a75805ca976c02f0abdb4b5b97e6']